/*
Integrations API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
)

// checks if the DataStorageLocation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DataStorageLocation{}

// DataStorageLocation Typed data-residency Location -- the region/country/state triple the SDK's “data_storage_location“ LocationSelect field carries (relyance_sdk “auth/integration_configs/common/region.py“: the canonical ROPA/DSR Location shape). Stored as a structured dict on the connection sub-doc; empty parts are dropped on write.
type DataStorageLocation struct {
	Region               NullableString `json:"region,omitempty"`
	Country              NullableString `json:"country,omitempty"`
	State                NullableString `json:"state,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _DataStorageLocation DataStorageLocation

// NewDataStorageLocation instantiates a new DataStorageLocation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDataStorageLocation() *DataStorageLocation {
	this := DataStorageLocation{}
	return &this
}

// NewDataStorageLocationWithDefaults instantiates a new DataStorageLocation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDataStorageLocationWithDefaults() *DataStorageLocation {
	this := DataStorageLocation{}
	return &this
}

// GetRegion returns the Region field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DataStorageLocation) GetRegion() string {
	if o == nil || IsNil(o.Region.Get()) {
		var ret string
		return ret
	}
	return *o.Region.Get()
}

// GetRegionOk returns a tuple with the Region field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DataStorageLocation) GetRegionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Region.Get(), o.Region.IsSet()
}

// HasRegion returns a boolean if a field has been set.
func (o *DataStorageLocation) HasRegion() bool {
	if o != nil && o.Region.IsSet() {
		return true
	}

	return false
}

// SetRegion gets a reference to the given NullableString and assigns it to the Region field.
func (o *DataStorageLocation) SetRegion(v string) {
	o.Region.Set(&v)
}

// SetRegionNil sets the value for Region to be an explicit nil
func (o *DataStorageLocation) SetRegionNil() {
	o.Region.Set(nil)
}

// UnsetRegion ensures that no value is present for Region, not even an explicit nil
func (o *DataStorageLocation) UnsetRegion() {
	o.Region.Unset()
}

// GetCountry returns the Country field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DataStorageLocation) GetCountry() string {
	if o == nil || IsNil(o.Country.Get()) {
		var ret string
		return ret
	}
	return *o.Country.Get()
}

// GetCountryOk returns a tuple with the Country field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DataStorageLocation) GetCountryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Country.Get(), o.Country.IsSet()
}

// HasCountry returns a boolean if a field has been set.
func (o *DataStorageLocation) HasCountry() bool {
	if o != nil && o.Country.IsSet() {
		return true
	}

	return false
}

// SetCountry gets a reference to the given NullableString and assigns it to the Country field.
func (o *DataStorageLocation) SetCountry(v string) {
	o.Country.Set(&v)
}

// SetCountryNil sets the value for Country to be an explicit nil
func (o *DataStorageLocation) SetCountryNil() {
	o.Country.Set(nil)
}

// UnsetCountry ensures that no value is present for Country, not even an explicit nil
func (o *DataStorageLocation) UnsetCountry() {
	o.Country.Unset()
}

// GetState returns the State field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DataStorageLocation) GetState() string {
	if o == nil || IsNil(o.State.Get()) {
		var ret string
		return ret
	}
	return *o.State.Get()
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DataStorageLocation) GetStateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.State.Get(), o.State.IsSet()
}

// HasState returns a boolean if a field has been set.
func (o *DataStorageLocation) HasState() bool {
	if o != nil && o.State.IsSet() {
		return true
	}

	return false
}

// SetState gets a reference to the given NullableString and assigns it to the State field.
func (o *DataStorageLocation) SetState(v string) {
	o.State.Set(&v)
}

// SetStateNil sets the value for State to be an explicit nil
func (o *DataStorageLocation) SetStateNil() {
	o.State.Set(nil)
}

// UnsetState ensures that no value is present for State, not even an explicit nil
func (o *DataStorageLocation) UnsetState() {
	o.State.Unset()
}

func (o DataStorageLocation) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DataStorageLocation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Region.IsSet() {
		toSerialize["region"] = o.Region.Get()
	}
	if o.Country.IsSet() {
		toSerialize["country"] = o.Country.Get()
	}
	if o.State.IsSet() {
		toSerialize["state"] = o.State.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *DataStorageLocation) UnmarshalJSON(data []byte) (err error) {
	varDataStorageLocation := _DataStorageLocation{}

	err = json.Unmarshal(data, &varDataStorageLocation)

	if err != nil {
		return err
	}

	*o = DataStorageLocation(varDataStorageLocation)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "region")
		delete(additionalProperties, "country")
		delete(additionalProperties, "state")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableDataStorageLocation struct {
	value *DataStorageLocation
	isSet bool
}

func (v NullableDataStorageLocation) Get() *DataStorageLocation {
	return v.value
}

func (v *NullableDataStorageLocation) Set(val *DataStorageLocation) {
	v.value = val
	v.isSet = true
}

func (v NullableDataStorageLocation) IsSet() bool {
	return v.isSet
}

func (v *NullableDataStorageLocation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDataStorageLocation(val *DataStorageLocation) *NullableDataStorageLocation {
	return &NullableDataStorageLocation{value: val, isSet: true}
}

func (v NullableDataStorageLocation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDataStorageLocation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
