/*
Integrations API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
	"fmt"
)

// checks if the ConnectionDetailSerializer type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConnectionDetailSerializer{}

// ConnectionDetailSerializer Connection sub-doc + masked auth configs + kind configs (all SDK-shaped, passthrough).
type ConnectionDetailSerializer struct {
	Connection           map[string]interface{}   `json:"connection"`
	AuthConfigs          []map[string]interface{} `json:"authConfigs,omitempty"`
	KindConfigs          []map[string]interface{} `json:"kindConfigs,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ConnectionDetailSerializer ConnectionDetailSerializer

// NewConnectionDetailSerializer instantiates a new ConnectionDetailSerializer object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConnectionDetailSerializer(connection map[string]interface{}) *ConnectionDetailSerializer {
	this := ConnectionDetailSerializer{}
	this.Connection = connection
	return &this
}

// NewConnectionDetailSerializerWithDefaults instantiates a new ConnectionDetailSerializer object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConnectionDetailSerializerWithDefaults() *ConnectionDetailSerializer {
	this := ConnectionDetailSerializer{}
	return &this
}

// GetConnection returns the Connection field value
func (o *ConnectionDetailSerializer) GetConnection() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Connection
}

// GetConnectionOk returns a tuple with the Connection field value
// and a boolean to check if the value has been set.
func (o *ConnectionDetailSerializer) GetConnectionOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Connection, true
}

// SetConnection sets field value
func (o *ConnectionDetailSerializer) SetConnection(v map[string]interface{}) {
	o.Connection = v
}

// GetAuthConfigs returns the AuthConfigs field value if set, zero value otherwise.
func (o *ConnectionDetailSerializer) GetAuthConfigs() []map[string]interface{} {
	if o == nil || IsNil(o.AuthConfigs) {
		var ret []map[string]interface{}
		return ret
	}
	return o.AuthConfigs
}

// GetAuthConfigsOk returns a tuple with the AuthConfigs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectionDetailSerializer) GetAuthConfigsOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.AuthConfigs) {
		return nil, false
	}
	return o.AuthConfigs, true
}

// HasAuthConfigs returns a boolean if a field has been set.
func (o *ConnectionDetailSerializer) HasAuthConfigs() bool {
	if o != nil && !IsNil(o.AuthConfigs) {
		return true
	}

	return false
}

// SetAuthConfigs gets a reference to the given []map[string]interface{} and assigns it to the AuthConfigs field.
func (o *ConnectionDetailSerializer) SetAuthConfigs(v []map[string]interface{}) {
	o.AuthConfigs = v
}

// GetKindConfigs returns the KindConfigs field value if set, zero value otherwise.
func (o *ConnectionDetailSerializer) GetKindConfigs() []map[string]interface{} {
	if o == nil || IsNil(o.KindConfigs) {
		var ret []map[string]interface{}
		return ret
	}
	return o.KindConfigs
}

// GetKindConfigsOk returns a tuple with the KindConfigs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectionDetailSerializer) GetKindConfigsOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.KindConfigs) {
		return nil, false
	}
	return o.KindConfigs, true
}

// HasKindConfigs returns a boolean if a field has been set.
func (o *ConnectionDetailSerializer) HasKindConfigs() bool {
	if o != nil && !IsNil(o.KindConfigs) {
		return true
	}

	return false
}

// SetKindConfigs gets a reference to the given []map[string]interface{} and assigns it to the KindConfigs field.
func (o *ConnectionDetailSerializer) SetKindConfigs(v []map[string]interface{}) {
	o.KindConfigs = v
}

func (o ConnectionDetailSerializer) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConnectionDetailSerializer) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["connection"] = o.Connection
	if !IsNil(o.AuthConfigs) {
		toSerialize["authConfigs"] = o.AuthConfigs
	}
	if !IsNil(o.KindConfigs) {
		toSerialize["kindConfigs"] = o.KindConfigs
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ConnectionDetailSerializer) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"connection",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varConnectionDetailSerializer := _ConnectionDetailSerializer{}

	err = json.Unmarshal(data, &varConnectionDetailSerializer)

	if err != nil {
		return err
	}

	*o = ConnectionDetailSerializer(varConnectionDetailSerializer)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "connection")
		delete(additionalProperties, "authConfigs")
		delete(additionalProperties, "kindConfigs")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableConnectionDetailSerializer struct {
	value *ConnectionDetailSerializer
	isSet bool
}

func (v NullableConnectionDetailSerializer) Get() *ConnectionDetailSerializer {
	return v.value
}

func (v *NullableConnectionDetailSerializer) Set(val *ConnectionDetailSerializer) {
	v.value = val
	v.isSet = true
}

func (v NullableConnectionDetailSerializer) IsSet() bool {
	return v.isSet
}

func (v *NullableConnectionDetailSerializer) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConnectionDetailSerializer(val *ConnectionDetailSerializer) *NullableConnectionDetailSerializer {
	return &NullableConnectionDetailSerializer{value: val, isSet: true}
}

func (v NullableConnectionDetailSerializer) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConnectionDetailSerializer) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
