/*
Integrations API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
	"fmt"
)

// checks if the AuthSaveRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuthSaveRequest{}

// AuthSaveRequest Mirrors “connSaveAuthParameters“'s “config“ argument.
type AuthSaveRequest struct {
	AuthKey              string                 `json:"authKey"`
	CustomCreds          map[string]interface{} `json:"customCreds,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _AuthSaveRequest AuthSaveRequest

// NewAuthSaveRequest instantiates a new AuthSaveRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthSaveRequest(authKey string) *AuthSaveRequest {
	this := AuthSaveRequest{}
	this.AuthKey = authKey
	return &this
}

// NewAuthSaveRequestWithDefaults instantiates a new AuthSaveRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthSaveRequestWithDefaults() *AuthSaveRequest {
	this := AuthSaveRequest{}
	return &this
}

// GetAuthKey returns the AuthKey field value
func (o *AuthSaveRequest) GetAuthKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AuthKey
}

// GetAuthKeyOk returns a tuple with the AuthKey field value
// and a boolean to check if the value has been set.
func (o *AuthSaveRequest) GetAuthKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AuthKey, true
}

// SetAuthKey sets field value
func (o *AuthSaveRequest) SetAuthKey(v string) {
	o.AuthKey = v
}

// GetCustomCreds returns the CustomCreds field value if set, zero value otherwise.
func (o *AuthSaveRequest) GetCustomCreds() map[string]interface{} {
	if o == nil || IsNil(o.CustomCreds) {
		var ret map[string]interface{}
		return ret
	}
	return o.CustomCreds
}

// GetCustomCredsOk returns a tuple with the CustomCreds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthSaveRequest) GetCustomCredsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.CustomCreds) {
		return map[string]interface{}{}, false
	}
	return o.CustomCreds, true
}

// HasCustomCreds returns a boolean if a field has been set.
func (o *AuthSaveRequest) HasCustomCreds() bool {
	if o != nil && !IsNil(o.CustomCreds) {
		return true
	}

	return false
}

// SetCustomCreds gets a reference to the given map[string]interface{} and assigns it to the CustomCreds field.
func (o *AuthSaveRequest) SetCustomCreds(v map[string]interface{}) {
	o.CustomCreds = v
}

func (o AuthSaveRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuthSaveRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["authKey"] = o.AuthKey
	if !IsNil(o.CustomCreds) {
		toSerialize["customCreds"] = o.CustomCreds
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AuthSaveRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"authKey",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAuthSaveRequest := _AuthSaveRequest{}

	err = json.Unmarshal(data, &varAuthSaveRequest)

	if err != nil {
		return err
	}

	*o = AuthSaveRequest(varAuthSaveRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "authKey")
		delete(additionalProperties, "customCreds")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAuthSaveRequest struct {
	value *AuthSaveRequest
	isSet bool
}

func (v NullableAuthSaveRequest) Get() *AuthSaveRequest {
	return v.value
}

func (v *NullableAuthSaveRequest) Set(val *AuthSaveRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthSaveRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthSaveRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthSaveRequest(val *AuthSaveRequest) *NullableAuthSaveRequest {
	return &NullableAuthSaveRequest{value: val, isSet: true}
}

func (v NullableAuthSaveRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthSaveRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
