/*
Integrations API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
	"fmt"
)

// checks if the PaginatedResponseSerializerBusinessNodeSerializer type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaginatedResponseSerializerBusinessNodeSerializer{}

// PaginatedResponseSerializerBusinessNodeSerializer struct for PaginatedResponseSerializerBusinessNodeSerializer
type PaginatedResponseSerializerBusinessNodeSerializer struct {
	TotalCount           int32                    `json:"total_count"`
	PageNum              int32                    `json:"page_num"`
	PageSize             int32                    `json:"page_size"`
	Results              []BusinessNodeSerializer `json:"results"`
	AdditionalProperties map[string]interface{}
}

type _PaginatedResponseSerializerBusinessNodeSerializer PaginatedResponseSerializerBusinessNodeSerializer

// NewPaginatedResponseSerializerBusinessNodeSerializer instantiates a new PaginatedResponseSerializerBusinessNodeSerializer object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaginatedResponseSerializerBusinessNodeSerializer(totalCount int32, pageNum int32, pageSize int32, results []BusinessNodeSerializer) *PaginatedResponseSerializerBusinessNodeSerializer {
	this := PaginatedResponseSerializerBusinessNodeSerializer{}
	this.TotalCount = totalCount
	this.PageNum = pageNum
	this.PageSize = pageSize
	this.Results = results
	return &this
}

// NewPaginatedResponseSerializerBusinessNodeSerializerWithDefaults instantiates a new PaginatedResponseSerializerBusinessNodeSerializer object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaginatedResponseSerializerBusinessNodeSerializerWithDefaults() *PaginatedResponseSerializerBusinessNodeSerializer {
	this := PaginatedResponseSerializerBusinessNodeSerializer{}
	return &this
}

// GetTotalCount returns the TotalCount field value
func (o *PaginatedResponseSerializerBusinessNodeSerializer) GetTotalCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TotalCount
}

// GetTotalCountOk returns a tuple with the TotalCount field value
// and a boolean to check if the value has been set.
func (o *PaginatedResponseSerializerBusinessNodeSerializer) GetTotalCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalCount, true
}

// SetTotalCount sets field value
func (o *PaginatedResponseSerializerBusinessNodeSerializer) SetTotalCount(v int32) {
	o.TotalCount = v
}

// GetPageNum returns the PageNum field value
func (o *PaginatedResponseSerializerBusinessNodeSerializer) GetPageNum() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PageNum
}

// GetPageNumOk returns a tuple with the PageNum field value
// and a boolean to check if the value has been set.
func (o *PaginatedResponseSerializerBusinessNodeSerializer) GetPageNumOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PageNum, true
}

// SetPageNum sets field value
func (o *PaginatedResponseSerializerBusinessNodeSerializer) SetPageNum(v int32) {
	o.PageNum = v
}

// GetPageSize returns the PageSize field value
func (o *PaginatedResponseSerializerBusinessNodeSerializer) GetPageSize() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PageSize
}

// GetPageSizeOk returns a tuple with the PageSize field value
// and a boolean to check if the value has been set.
func (o *PaginatedResponseSerializerBusinessNodeSerializer) GetPageSizeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PageSize, true
}

// SetPageSize sets field value
func (o *PaginatedResponseSerializerBusinessNodeSerializer) SetPageSize(v int32) {
	o.PageSize = v
}

// GetResults returns the Results field value
func (o *PaginatedResponseSerializerBusinessNodeSerializer) GetResults() []BusinessNodeSerializer {
	if o == nil {
		var ret []BusinessNodeSerializer
		return ret
	}

	return o.Results
}

// GetResultsOk returns a tuple with the Results field value
// and a boolean to check if the value has been set.
func (o *PaginatedResponseSerializerBusinessNodeSerializer) GetResultsOk() ([]BusinessNodeSerializer, bool) {
	if o == nil {
		return nil, false
	}
	return o.Results, true
}

// SetResults sets field value
func (o *PaginatedResponseSerializerBusinessNodeSerializer) SetResults(v []BusinessNodeSerializer) {
	o.Results = v
}

func (o PaginatedResponseSerializerBusinessNodeSerializer) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaginatedResponseSerializerBusinessNodeSerializer) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["total_count"] = o.TotalCount
	toSerialize["page_num"] = o.PageNum
	toSerialize["page_size"] = o.PageSize
	toSerialize["results"] = o.Results

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PaginatedResponseSerializerBusinessNodeSerializer) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"total_count",
		"page_num",
		"page_size",
		"results",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPaginatedResponseSerializerBusinessNodeSerializer := _PaginatedResponseSerializerBusinessNodeSerializer{}

	err = json.Unmarshal(data, &varPaginatedResponseSerializerBusinessNodeSerializer)

	if err != nil {
		return err
	}

	*o = PaginatedResponseSerializerBusinessNodeSerializer(varPaginatedResponseSerializerBusinessNodeSerializer)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "total_count")
		delete(additionalProperties, "page_num")
		delete(additionalProperties, "page_size")
		delete(additionalProperties, "results")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePaginatedResponseSerializerBusinessNodeSerializer struct {
	value *PaginatedResponseSerializerBusinessNodeSerializer
	isSet bool
}

func (v NullablePaginatedResponseSerializerBusinessNodeSerializer) Get() *PaginatedResponseSerializerBusinessNodeSerializer {
	return v.value
}

func (v *NullablePaginatedResponseSerializerBusinessNodeSerializer) Set(val *PaginatedResponseSerializerBusinessNodeSerializer) {
	v.value = val
	v.isSet = true
}

func (v NullablePaginatedResponseSerializerBusinessNodeSerializer) IsSet() bool {
	return v.isSet
}

func (v *NullablePaginatedResponseSerializerBusinessNodeSerializer) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaginatedResponseSerializerBusinessNodeSerializer(val *PaginatedResponseSerializerBusinessNodeSerializer) *NullablePaginatedResponseSerializerBusinessNodeSerializer {
	return &NullablePaginatedResponseSerializerBusinessNodeSerializer{value: val, isSet: true}
}

func (v NullablePaginatedResponseSerializerBusinessNodeSerializer) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaginatedResponseSerializerBusinessNodeSerializer) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
