/*
Integrations API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
	"fmt"
)

// checks if the BusinessNodeSerializer type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BusinessNodeSerializer{}

// BusinessNodeSerializer Mirrors “models.business_nodes.BusinessNode“ - including its vendor-doc fallback logic for “BUSINESS_ENTITY“ nodes, applied via a context-aware “model_validator(mode='after')“ exactly as the original does.
type BusinessNodeSerializer struct {
	RecordId string `json:"record_id"`
	Name     string `json:"name"`
	// Business node type (e.g. TYPE_BUSINESS_ENTITY, TYPE_PRODUCT). Served as an open string so new server-side types never break deserialization in already-shipped clients.
	Type                 string         `json:"type"`
	Vendors              []string       `json:"vendors,omitempty"`
	Services             []string       `json:"services,omitempty"`
	ProcessingActivities []string       `json:"processing_activities,omitempty"`
	Description          NullableString `json:"description,omitempty"`
	BusinessModels       []string       `json:"business_models,omitempty"`
	CreatedDate          NullableInt32  `json:"created_date,omitempty"`
	UpdatedDate          NullableInt32  `json:"updated_date,omitempty"`
	Parent               NullableString `json:"parent,omitempty"`
	Sources              []string       `json:"sources,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _BusinessNodeSerializer BusinessNodeSerializer

// NewBusinessNodeSerializer instantiates a new BusinessNodeSerializer object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBusinessNodeSerializer(recordId string, name string, type_ string) *BusinessNodeSerializer {
	this := BusinessNodeSerializer{}
	this.RecordId = recordId
	this.Name = name
	this.Type = type_
	return &this
}

// NewBusinessNodeSerializerWithDefaults instantiates a new BusinessNodeSerializer object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBusinessNodeSerializerWithDefaults() *BusinessNodeSerializer {
	this := BusinessNodeSerializer{}
	return &this
}

// GetRecordId returns the RecordId field value
func (o *BusinessNodeSerializer) GetRecordId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RecordId
}

// GetRecordIdOk returns a tuple with the RecordId field value
// and a boolean to check if the value has been set.
func (o *BusinessNodeSerializer) GetRecordIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RecordId, true
}

// SetRecordId sets field value
func (o *BusinessNodeSerializer) SetRecordId(v string) {
	o.RecordId = v
}

// GetName returns the Name field value
func (o *BusinessNodeSerializer) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *BusinessNodeSerializer) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *BusinessNodeSerializer) SetName(v string) {
	o.Name = v
}

// GetType returns the Type field value
func (o *BusinessNodeSerializer) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *BusinessNodeSerializer) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *BusinessNodeSerializer) SetType(v string) {
	o.Type = v
}

// GetVendors returns the Vendors field value if set, zero value otherwise.
func (o *BusinessNodeSerializer) GetVendors() []string {
	if o == nil || IsNil(o.Vendors) {
		var ret []string
		return ret
	}
	return o.Vendors
}

// GetVendorsOk returns a tuple with the Vendors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BusinessNodeSerializer) GetVendorsOk() ([]string, bool) {
	if o == nil || IsNil(o.Vendors) {
		return nil, false
	}
	return o.Vendors, true
}

// HasVendors returns a boolean if a field has been set.
func (o *BusinessNodeSerializer) HasVendors() bool {
	if o != nil && !IsNil(o.Vendors) {
		return true
	}

	return false
}

// SetVendors gets a reference to the given []string and assigns it to the Vendors field.
func (o *BusinessNodeSerializer) SetVendors(v []string) {
	o.Vendors = v
}

// GetServices returns the Services field value if set, zero value otherwise.
func (o *BusinessNodeSerializer) GetServices() []string {
	if o == nil || IsNil(o.Services) {
		var ret []string
		return ret
	}
	return o.Services
}

// GetServicesOk returns a tuple with the Services field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BusinessNodeSerializer) GetServicesOk() ([]string, bool) {
	if o == nil || IsNil(o.Services) {
		return nil, false
	}
	return o.Services, true
}

// HasServices returns a boolean if a field has been set.
func (o *BusinessNodeSerializer) HasServices() bool {
	if o != nil && !IsNil(o.Services) {
		return true
	}

	return false
}

// SetServices gets a reference to the given []string and assigns it to the Services field.
func (o *BusinessNodeSerializer) SetServices(v []string) {
	o.Services = v
}

// GetProcessingActivities returns the ProcessingActivities field value if set, zero value otherwise.
func (o *BusinessNodeSerializer) GetProcessingActivities() []string {
	if o == nil || IsNil(o.ProcessingActivities) {
		var ret []string
		return ret
	}
	return o.ProcessingActivities
}

// GetProcessingActivitiesOk returns a tuple with the ProcessingActivities field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BusinessNodeSerializer) GetProcessingActivitiesOk() ([]string, bool) {
	if o == nil || IsNil(o.ProcessingActivities) {
		return nil, false
	}
	return o.ProcessingActivities, true
}

// HasProcessingActivities returns a boolean if a field has been set.
func (o *BusinessNodeSerializer) HasProcessingActivities() bool {
	if o != nil && !IsNil(o.ProcessingActivities) {
		return true
	}

	return false
}

// SetProcessingActivities gets a reference to the given []string and assigns it to the ProcessingActivities field.
func (o *BusinessNodeSerializer) SetProcessingActivities(v []string) {
	o.ProcessingActivities = v
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BusinessNodeSerializer) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BusinessNodeSerializer) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *BusinessNodeSerializer) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *BusinessNodeSerializer) SetDescription(v string) {
	o.Description.Set(&v)
}

// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *BusinessNodeSerializer) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *BusinessNodeSerializer) UnsetDescription() {
	o.Description.Unset()
}

// GetBusinessModels returns the BusinessModels field value if set, zero value otherwise.
func (o *BusinessNodeSerializer) GetBusinessModels() []string {
	if o == nil || IsNil(o.BusinessModels) {
		var ret []string
		return ret
	}
	return o.BusinessModels
}

// GetBusinessModelsOk returns a tuple with the BusinessModels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BusinessNodeSerializer) GetBusinessModelsOk() ([]string, bool) {
	if o == nil || IsNil(o.BusinessModels) {
		return nil, false
	}
	return o.BusinessModels, true
}

// HasBusinessModels returns a boolean if a field has been set.
func (o *BusinessNodeSerializer) HasBusinessModels() bool {
	if o != nil && !IsNil(o.BusinessModels) {
		return true
	}

	return false
}

// SetBusinessModels gets a reference to the given []string and assigns it to the BusinessModels field.
func (o *BusinessNodeSerializer) SetBusinessModels(v []string) {
	o.BusinessModels = v
}

// GetCreatedDate returns the CreatedDate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BusinessNodeSerializer) GetCreatedDate() int32 {
	if o == nil || IsNil(o.CreatedDate.Get()) {
		var ret int32
		return ret
	}
	return *o.CreatedDate.Get()
}

// GetCreatedDateOk returns a tuple with the CreatedDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BusinessNodeSerializer) GetCreatedDateOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.CreatedDate.Get(), o.CreatedDate.IsSet()
}

// HasCreatedDate returns a boolean if a field has been set.
func (o *BusinessNodeSerializer) HasCreatedDate() bool {
	if o != nil && o.CreatedDate.IsSet() {
		return true
	}

	return false
}

// SetCreatedDate gets a reference to the given NullableInt32 and assigns it to the CreatedDate field.
func (o *BusinessNodeSerializer) SetCreatedDate(v int32) {
	o.CreatedDate.Set(&v)
}

// SetCreatedDateNil sets the value for CreatedDate to be an explicit nil
func (o *BusinessNodeSerializer) SetCreatedDateNil() {
	o.CreatedDate.Set(nil)
}

// UnsetCreatedDate ensures that no value is present for CreatedDate, not even an explicit nil
func (o *BusinessNodeSerializer) UnsetCreatedDate() {
	o.CreatedDate.Unset()
}

// GetUpdatedDate returns the UpdatedDate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BusinessNodeSerializer) GetUpdatedDate() int32 {
	if o == nil || IsNil(o.UpdatedDate.Get()) {
		var ret int32
		return ret
	}
	return *o.UpdatedDate.Get()
}

// GetUpdatedDateOk returns a tuple with the UpdatedDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BusinessNodeSerializer) GetUpdatedDateOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.UpdatedDate.Get(), o.UpdatedDate.IsSet()
}

// HasUpdatedDate returns a boolean if a field has been set.
func (o *BusinessNodeSerializer) HasUpdatedDate() bool {
	if o != nil && o.UpdatedDate.IsSet() {
		return true
	}

	return false
}

// SetUpdatedDate gets a reference to the given NullableInt32 and assigns it to the UpdatedDate field.
func (o *BusinessNodeSerializer) SetUpdatedDate(v int32) {
	o.UpdatedDate.Set(&v)
}

// SetUpdatedDateNil sets the value for UpdatedDate to be an explicit nil
func (o *BusinessNodeSerializer) SetUpdatedDateNil() {
	o.UpdatedDate.Set(nil)
}

// UnsetUpdatedDate ensures that no value is present for UpdatedDate, not even an explicit nil
func (o *BusinessNodeSerializer) UnsetUpdatedDate() {
	o.UpdatedDate.Unset()
}

// GetParent returns the Parent field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BusinessNodeSerializer) GetParent() string {
	if o == nil || IsNil(o.Parent.Get()) {
		var ret string
		return ret
	}
	return *o.Parent.Get()
}

// GetParentOk returns a tuple with the Parent field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BusinessNodeSerializer) GetParentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Parent.Get(), o.Parent.IsSet()
}

// HasParent returns a boolean if a field has been set.
func (o *BusinessNodeSerializer) HasParent() bool {
	if o != nil && o.Parent.IsSet() {
		return true
	}

	return false
}

// SetParent gets a reference to the given NullableString and assigns it to the Parent field.
func (o *BusinessNodeSerializer) SetParent(v string) {
	o.Parent.Set(&v)
}

// SetParentNil sets the value for Parent to be an explicit nil
func (o *BusinessNodeSerializer) SetParentNil() {
	o.Parent.Set(nil)
}

// UnsetParent ensures that no value is present for Parent, not even an explicit nil
func (o *BusinessNodeSerializer) UnsetParent() {
	o.Parent.Unset()
}

// GetSources returns the Sources field value if set, zero value otherwise.
func (o *BusinessNodeSerializer) GetSources() []string {
	if o == nil || IsNil(o.Sources) {
		var ret []string
		return ret
	}
	return o.Sources
}

// GetSourcesOk returns a tuple with the Sources field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BusinessNodeSerializer) GetSourcesOk() ([]string, bool) {
	if o == nil || IsNil(o.Sources) {
		return nil, false
	}
	return o.Sources, true
}

// HasSources returns a boolean if a field has been set.
func (o *BusinessNodeSerializer) HasSources() bool {
	if o != nil && !IsNil(o.Sources) {
		return true
	}

	return false
}

// SetSources gets a reference to the given []string and assigns it to the Sources field.
func (o *BusinessNodeSerializer) SetSources(v []string) {
	o.Sources = v
}

func (o BusinessNodeSerializer) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BusinessNodeSerializer) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["record_id"] = o.RecordId
	toSerialize["name"] = o.Name
	toSerialize["type"] = o.Type
	if !IsNil(o.Vendors) {
		toSerialize["vendors"] = o.Vendors
	}
	if !IsNil(o.Services) {
		toSerialize["services"] = o.Services
	}
	if !IsNil(o.ProcessingActivities) {
		toSerialize["processing_activities"] = o.ProcessingActivities
	}
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	if !IsNil(o.BusinessModels) {
		toSerialize["business_models"] = o.BusinessModels
	}
	if o.CreatedDate.IsSet() {
		toSerialize["created_date"] = o.CreatedDate.Get()
	}
	if o.UpdatedDate.IsSet() {
		toSerialize["updated_date"] = o.UpdatedDate.Get()
	}
	if o.Parent.IsSet() {
		toSerialize["parent"] = o.Parent.Get()
	}
	if !IsNil(o.Sources) {
		toSerialize["sources"] = o.Sources
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *BusinessNodeSerializer) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"record_id",
		"name",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBusinessNodeSerializer := _BusinessNodeSerializer{}

	err = json.Unmarshal(data, &varBusinessNodeSerializer)

	if err != nil {
		return err
	}

	*o = BusinessNodeSerializer(varBusinessNodeSerializer)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "record_id")
		delete(additionalProperties, "name")
		delete(additionalProperties, "type")
		delete(additionalProperties, "vendors")
		delete(additionalProperties, "services")
		delete(additionalProperties, "processing_activities")
		delete(additionalProperties, "description")
		delete(additionalProperties, "business_models")
		delete(additionalProperties, "created_date")
		delete(additionalProperties, "updated_date")
		delete(additionalProperties, "parent")
		delete(additionalProperties, "sources")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableBusinessNodeSerializer struct {
	value *BusinessNodeSerializer
	isSet bool
}

func (v NullableBusinessNodeSerializer) Get() *BusinessNodeSerializer {
	return v.value
}

func (v *NullableBusinessNodeSerializer) Set(val *BusinessNodeSerializer) {
	v.value = val
	v.isSet = true
}

func (v NullableBusinessNodeSerializer) IsSet() bool {
	return v.isSet
}

func (v *NullableBusinessNodeSerializer) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBusinessNodeSerializer(val *BusinessNodeSerializer) *NullableBusinessNodeSerializer {
	return &NullableBusinessNodeSerializer{value: val, isSet: true}
}

func (v NullableBusinessNodeSerializer) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBusinessNodeSerializer) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
