/*
Integrations API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
)

// checks if the ScalarUpdateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ScalarUpdateRequest{}

// ScalarUpdateRequest Consolidated single-field setters -- mirrors “connSetName“/“connSetRefreshFrequency“/ “connSetStartScanFrom“/“connSetDataStorageLocation“/“connSetBusinessNodeIds“/ “connSetCredentialsExpireAt“/“connUpdateRelyanceSecretAccess“. Every field is optional; only the ones present in the request are written.
type ScalarUpdateRequest struct {
	ConnectionName       NullableString              `json:"connectionName,omitempty"`
	RefreshFrequency     NullableInt64               `json:"refreshFrequency,omitempty"`
	StartScanFrom        NullableFloat64             `json:"startScanFrom,omitempty"`
	DataStorageLocation  NullableDataStorageLocation `json:"dataStorageLocation,omitempty"`
	BusinessNodeIds      []string                    `json:"businessNodeIds,omitempty"`
	CredentialsExpireAt  NullableInt64               `json:"credentialsExpireAt,omitempty"`
	RelyanceSecretAccess NullableBool                `json:"relyanceSecretAccess,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ScalarUpdateRequest ScalarUpdateRequest

// NewScalarUpdateRequest instantiates a new ScalarUpdateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewScalarUpdateRequest() *ScalarUpdateRequest {
	this := ScalarUpdateRequest{}
	return &this
}

// NewScalarUpdateRequestWithDefaults instantiates a new ScalarUpdateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewScalarUpdateRequestWithDefaults() *ScalarUpdateRequest {
	this := ScalarUpdateRequest{}
	return &this
}

// GetConnectionName returns the ConnectionName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ScalarUpdateRequest) GetConnectionName() string {
	if o == nil || IsNil(o.ConnectionName.Get()) {
		var ret string
		return ret
	}
	return *o.ConnectionName.Get()
}

// GetConnectionNameOk returns a tuple with the ConnectionName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ScalarUpdateRequest) GetConnectionNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ConnectionName.Get(), o.ConnectionName.IsSet()
}

// HasConnectionName returns a boolean if a field has been set.
func (o *ScalarUpdateRequest) HasConnectionName() bool {
	if o != nil && o.ConnectionName.IsSet() {
		return true
	}

	return false
}

// SetConnectionName gets a reference to the given NullableString and assigns it to the ConnectionName field.
func (o *ScalarUpdateRequest) SetConnectionName(v string) {
	o.ConnectionName.Set(&v)
}

// SetConnectionNameNil sets the value for ConnectionName to be an explicit nil
func (o *ScalarUpdateRequest) SetConnectionNameNil() {
	o.ConnectionName.Set(nil)
}

// UnsetConnectionName ensures that no value is present for ConnectionName, not even an explicit nil
func (o *ScalarUpdateRequest) UnsetConnectionName() {
	o.ConnectionName.Unset()
}

// GetRefreshFrequency returns the RefreshFrequency field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ScalarUpdateRequest) GetRefreshFrequency() int64 {
	if o == nil || IsNil(o.RefreshFrequency.Get()) {
		var ret int64
		return ret
	}
	return *o.RefreshFrequency.Get()
}

// GetRefreshFrequencyOk returns a tuple with the RefreshFrequency field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ScalarUpdateRequest) GetRefreshFrequencyOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.RefreshFrequency.Get(), o.RefreshFrequency.IsSet()
}

// HasRefreshFrequency returns a boolean if a field has been set.
func (o *ScalarUpdateRequest) HasRefreshFrequency() bool {
	if o != nil && o.RefreshFrequency.IsSet() {
		return true
	}

	return false
}

// SetRefreshFrequency gets a reference to the given NullableInt64 and assigns it to the RefreshFrequency field.
func (o *ScalarUpdateRequest) SetRefreshFrequency(v int64) {
	o.RefreshFrequency.Set(&v)
}

// SetRefreshFrequencyNil sets the value for RefreshFrequency to be an explicit nil
func (o *ScalarUpdateRequest) SetRefreshFrequencyNil() {
	o.RefreshFrequency.Set(nil)
}

// UnsetRefreshFrequency ensures that no value is present for RefreshFrequency, not even an explicit nil
func (o *ScalarUpdateRequest) UnsetRefreshFrequency() {
	o.RefreshFrequency.Unset()
}

// GetStartScanFrom returns the StartScanFrom field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ScalarUpdateRequest) GetStartScanFrom() float64 {
	if o == nil || IsNil(o.StartScanFrom.Get()) {
		var ret float64
		return ret
	}
	return *o.StartScanFrom.Get()
}

// GetStartScanFromOk returns a tuple with the StartScanFrom field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ScalarUpdateRequest) GetStartScanFromOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return o.StartScanFrom.Get(), o.StartScanFrom.IsSet()
}

// HasStartScanFrom returns a boolean if a field has been set.
func (o *ScalarUpdateRequest) HasStartScanFrom() bool {
	if o != nil && o.StartScanFrom.IsSet() {
		return true
	}

	return false
}

// SetStartScanFrom gets a reference to the given NullableFloat64 and assigns it to the StartScanFrom field.
func (o *ScalarUpdateRequest) SetStartScanFrom(v float64) {
	o.StartScanFrom.Set(&v)
}

// SetStartScanFromNil sets the value for StartScanFrom to be an explicit nil
func (o *ScalarUpdateRequest) SetStartScanFromNil() {
	o.StartScanFrom.Set(nil)
}

// UnsetStartScanFrom ensures that no value is present for StartScanFrom, not even an explicit nil
func (o *ScalarUpdateRequest) UnsetStartScanFrom() {
	o.StartScanFrom.Unset()
}

// GetDataStorageLocation returns the DataStorageLocation field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ScalarUpdateRequest) GetDataStorageLocation() DataStorageLocation {
	if o == nil || IsNil(o.DataStorageLocation.Get()) {
		var ret DataStorageLocation
		return ret
	}
	return *o.DataStorageLocation.Get()
}

// GetDataStorageLocationOk returns a tuple with the DataStorageLocation field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ScalarUpdateRequest) GetDataStorageLocationOk() (*DataStorageLocation, bool) {
	if o == nil {
		return nil, false
	}
	return o.DataStorageLocation.Get(), o.DataStorageLocation.IsSet()
}

// HasDataStorageLocation returns a boolean if a field has been set.
func (o *ScalarUpdateRequest) HasDataStorageLocation() bool {
	if o != nil && o.DataStorageLocation.IsSet() {
		return true
	}

	return false
}

// SetDataStorageLocation gets a reference to the given NullableDataStorageLocation and assigns it to the DataStorageLocation field.
func (o *ScalarUpdateRequest) SetDataStorageLocation(v DataStorageLocation) {
	o.DataStorageLocation.Set(&v)
}

// SetDataStorageLocationNil sets the value for DataStorageLocation to be an explicit nil
func (o *ScalarUpdateRequest) SetDataStorageLocationNil() {
	o.DataStorageLocation.Set(nil)
}

// UnsetDataStorageLocation ensures that no value is present for DataStorageLocation, not even an explicit nil
func (o *ScalarUpdateRequest) UnsetDataStorageLocation() {
	o.DataStorageLocation.Unset()
}

// GetBusinessNodeIds returns the BusinessNodeIds field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ScalarUpdateRequest) GetBusinessNodeIds() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.BusinessNodeIds
}

// GetBusinessNodeIdsOk returns a tuple with the BusinessNodeIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ScalarUpdateRequest) GetBusinessNodeIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.BusinessNodeIds) {
		return nil, false
	}
	return o.BusinessNodeIds, true
}

// HasBusinessNodeIds returns a boolean if a field has been set.
func (o *ScalarUpdateRequest) HasBusinessNodeIds() bool {
	if o != nil && !IsNil(o.BusinessNodeIds) {
		return true
	}

	return false
}

// SetBusinessNodeIds gets a reference to the given []string and assigns it to the BusinessNodeIds field.
func (o *ScalarUpdateRequest) SetBusinessNodeIds(v []string) {
	o.BusinessNodeIds = v
}

// GetCredentialsExpireAt returns the CredentialsExpireAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ScalarUpdateRequest) GetCredentialsExpireAt() int64 {
	if o == nil || IsNil(o.CredentialsExpireAt.Get()) {
		var ret int64
		return ret
	}
	return *o.CredentialsExpireAt.Get()
}

// GetCredentialsExpireAtOk returns a tuple with the CredentialsExpireAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ScalarUpdateRequest) GetCredentialsExpireAtOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.CredentialsExpireAt.Get(), o.CredentialsExpireAt.IsSet()
}

// HasCredentialsExpireAt returns a boolean if a field has been set.
func (o *ScalarUpdateRequest) HasCredentialsExpireAt() bool {
	if o != nil && o.CredentialsExpireAt.IsSet() {
		return true
	}

	return false
}

// SetCredentialsExpireAt gets a reference to the given NullableInt64 and assigns it to the CredentialsExpireAt field.
func (o *ScalarUpdateRequest) SetCredentialsExpireAt(v int64) {
	o.CredentialsExpireAt.Set(&v)
}

// SetCredentialsExpireAtNil sets the value for CredentialsExpireAt to be an explicit nil
func (o *ScalarUpdateRequest) SetCredentialsExpireAtNil() {
	o.CredentialsExpireAt.Set(nil)
}

// UnsetCredentialsExpireAt ensures that no value is present for CredentialsExpireAt, not even an explicit nil
func (o *ScalarUpdateRequest) UnsetCredentialsExpireAt() {
	o.CredentialsExpireAt.Unset()
}

// GetRelyanceSecretAccess returns the RelyanceSecretAccess field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ScalarUpdateRequest) GetRelyanceSecretAccess() bool {
	if o == nil || IsNil(o.RelyanceSecretAccess.Get()) {
		var ret bool
		return ret
	}
	return *o.RelyanceSecretAccess.Get()
}

// GetRelyanceSecretAccessOk returns a tuple with the RelyanceSecretAccess field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ScalarUpdateRequest) GetRelyanceSecretAccessOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.RelyanceSecretAccess.Get(), o.RelyanceSecretAccess.IsSet()
}

// HasRelyanceSecretAccess returns a boolean if a field has been set.
func (o *ScalarUpdateRequest) HasRelyanceSecretAccess() bool {
	if o != nil && o.RelyanceSecretAccess.IsSet() {
		return true
	}

	return false
}

// SetRelyanceSecretAccess gets a reference to the given NullableBool and assigns it to the RelyanceSecretAccess field.
func (o *ScalarUpdateRequest) SetRelyanceSecretAccess(v bool) {
	o.RelyanceSecretAccess.Set(&v)
}

// SetRelyanceSecretAccessNil sets the value for RelyanceSecretAccess to be an explicit nil
func (o *ScalarUpdateRequest) SetRelyanceSecretAccessNil() {
	o.RelyanceSecretAccess.Set(nil)
}

// UnsetRelyanceSecretAccess ensures that no value is present for RelyanceSecretAccess, not even an explicit nil
func (o *ScalarUpdateRequest) UnsetRelyanceSecretAccess() {
	o.RelyanceSecretAccess.Unset()
}

func (o ScalarUpdateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ScalarUpdateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.ConnectionName.IsSet() {
		toSerialize["connectionName"] = o.ConnectionName.Get()
	}
	if o.RefreshFrequency.IsSet() {
		toSerialize["refreshFrequency"] = o.RefreshFrequency.Get()
	}
	if o.StartScanFrom.IsSet() {
		toSerialize["startScanFrom"] = o.StartScanFrom.Get()
	}
	if o.DataStorageLocation.IsSet() {
		toSerialize["dataStorageLocation"] = o.DataStorageLocation.Get()
	}
	if o.BusinessNodeIds != nil {
		toSerialize["businessNodeIds"] = o.BusinessNodeIds
	}
	if o.CredentialsExpireAt.IsSet() {
		toSerialize["credentialsExpireAt"] = o.CredentialsExpireAt.Get()
	}
	if o.RelyanceSecretAccess.IsSet() {
		toSerialize["relyanceSecretAccess"] = o.RelyanceSecretAccess.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ScalarUpdateRequest) UnmarshalJSON(data []byte) (err error) {
	varScalarUpdateRequest := _ScalarUpdateRequest{}

	err = json.Unmarshal(data, &varScalarUpdateRequest)

	if err != nil {
		return err
	}

	*o = ScalarUpdateRequest(varScalarUpdateRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "connectionName")
		delete(additionalProperties, "refreshFrequency")
		delete(additionalProperties, "startScanFrom")
		delete(additionalProperties, "dataStorageLocation")
		delete(additionalProperties, "businessNodeIds")
		delete(additionalProperties, "credentialsExpireAt")
		delete(additionalProperties, "relyanceSecretAccess")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableScalarUpdateRequest struct {
	value *ScalarUpdateRequest
	isSet bool
}

func (v NullableScalarUpdateRequest) Get() *ScalarUpdateRequest {
	return v.value
}

func (v *NullableScalarUpdateRequest) Set(val *ScalarUpdateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableScalarUpdateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableScalarUpdateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableScalarUpdateRequest(val *ScalarUpdateRequest) *NullableScalarUpdateRequest {
	return &NullableScalarUpdateRequest{value: val, isSet: true}
}

func (v NullableScalarUpdateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableScalarUpdateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
