/*
Integrations API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
	"fmt"
)

// checks if the ConnectResponseSerializer type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConnectResponseSerializer{}

// ConnectResponseSerializer 202 body for “POST .../connect“ -- a monitor representation of the in-flight attempt (the live test itself runs in the background; poll “GET .../{connection_id}“ for the eventual result).
type ConnectResponseSerializer struct {
	Id                   string  `json:"id"`
	Status               *string `json:"status,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ConnectResponseSerializer ConnectResponseSerializer

// NewConnectResponseSerializer instantiates a new ConnectResponseSerializer object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConnectResponseSerializer(id string) *ConnectResponseSerializer {
	this := ConnectResponseSerializer{}
	this.Id = id
	var status string = "connecting"
	this.Status = &status
	return &this
}

// NewConnectResponseSerializerWithDefaults instantiates a new ConnectResponseSerializer object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConnectResponseSerializerWithDefaults() *ConnectResponseSerializer {
	this := ConnectResponseSerializer{}
	var status string = "connecting"
	this.Status = &status
	return &this
}

// GetId returns the Id field value
func (o *ConnectResponseSerializer) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ConnectResponseSerializer) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ConnectResponseSerializer) SetId(v string) {
	o.Id = v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *ConnectResponseSerializer) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectResponseSerializer) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *ConnectResponseSerializer) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *ConnectResponseSerializer) SetStatus(v string) {
	o.Status = &v
}

func (o ConnectResponseSerializer) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConnectResponseSerializer) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ConnectResponseSerializer) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varConnectResponseSerializer := _ConnectResponseSerializer{}

	err = json.Unmarshal(data, &varConnectResponseSerializer)

	if err != nil {
		return err
	}

	*o = ConnectResponseSerializer(varConnectResponseSerializer)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "status")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableConnectResponseSerializer struct {
	value *ConnectResponseSerializer
	isSet bool
}

func (v NullableConnectResponseSerializer) Get() *ConnectResponseSerializer {
	return v.value
}

func (v *NullableConnectResponseSerializer) Set(val *ConnectResponseSerializer) {
	v.value = val
	v.isSet = true
}

func (v NullableConnectResponseSerializer) IsSet() bool {
	return v.isSet
}

func (v *NullableConnectResponseSerializer) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConnectResponseSerializer(val *ConnectResponseSerializer) *NullableConnectResponseSerializer {
	return &NullableConnectResponseSerializer{value: val, isSet: true}
}

func (v NullableConnectResponseSerializer) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConnectResponseSerializer) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
