/*
Integrations API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
	"fmt"
)

// checks if the AuthValidateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuthValidateRequest{}

// AuthValidateRequest Mirrors “connValidateAuthParameters“'s “config“ argument.
type AuthValidateRequest struct {
	// The vendor auth config's key (stored at connection.auth.type).
	AuthKey              string                 `json:"authKey"`
	CustomCreds          map[string]interface{} `json:"customCreds,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _AuthValidateRequest AuthValidateRequest

// NewAuthValidateRequest instantiates a new AuthValidateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthValidateRequest(authKey string) *AuthValidateRequest {
	this := AuthValidateRequest{}
	this.AuthKey = authKey
	return &this
}

// NewAuthValidateRequestWithDefaults instantiates a new AuthValidateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthValidateRequestWithDefaults() *AuthValidateRequest {
	this := AuthValidateRequest{}
	return &this
}

// GetAuthKey returns the AuthKey field value
func (o *AuthValidateRequest) GetAuthKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AuthKey
}

// GetAuthKeyOk returns a tuple with the AuthKey field value
// and a boolean to check if the value has been set.
func (o *AuthValidateRequest) GetAuthKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AuthKey, true
}

// SetAuthKey sets field value
func (o *AuthValidateRequest) SetAuthKey(v string) {
	o.AuthKey = v
}

// GetCustomCreds returns the CustomCreds field value if set, zero value otherwise.
func (o *AuthValidateRequest) GetCustomCreds() map[string]interface{} {
	if o == nil || IsNil(o.CustomCreds) {
		var ret map[string]interface{}
		return ret
	}
	return o.CustomCreds
}

// GetCustomCredsOk returns a tuple with the CustomCreds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthValidateRequest) GetCustomCredsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.CustomCreds) {
		return map[string]interface{}{}, false
	}
	return o.CustomCreds, true
}

// HasCustomCreds returns a boolean if a field has been set.
func (o *AuthValidateRequest) HasCustomCreds() bool {
	if o != nil && !IsNil(o.CustomCreds) {
		return true
	}

	return false
}

// SetCustomCreds gets a reference to the given map[string]interface{} and assigns it to the CustomCreds field.
func (o *AuthValidateRequest) SetCustomCreds(v map[string]interface{}) {
	o.CustomCreds = v
}

func (o AuthValidateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuthValidateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["authKey"] = o.AuthKey
	if !IsNil(o.CustomCreds) {
		toSerialize["customCreds"] = o.CustomCreds
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AuthValidateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"authKey",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAuthValidateRequest := _AuthValidateRequest{}

	err = json.Unmarshal(data, &varAuthValidateRequest)

	if err != nil {
		return err
	}

	*o = AuthValidateRequest(varAuthValidateRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "authKey")
		delete(additionalProperties, "customCreds")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAuthValidateRequest struct {
	value *AuthValidateRequest
	isSet bool
}

func (v NullableAuthValidateRequest) Get() *AuthValidateRequest {
	return v.value
}

func (v *NullableAuthValidateRequest) Set(val *AuthValidateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthValidateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthValidateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthValidateRequest(val *AuthValidateRequest) *NullableAuthValidateRequest {
	return &NullableAuthValidateRequest{value: val, isSet: true}
}

func (v NullableAuthValidateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthValidateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
