/*
Integrations API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
)

// checks if the KindValidateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &KindValidateRequest{}

// KindValidateRequest struct for KindValidateRequest
type KindValidateRequest struct {
	Parameters           map[string]interface{} `json:"parameters,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _KindValidateRequest KindValidateRequest

// NewKindValidateRequest instantiates a new KindValidateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKindValidateRequest() *KindValidateRequest {
	this := KindValidateRequest{}
	return &this
}

// NewKindValidateRequestWithDefaults instantiates a new KindValidateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKindValidateRequestWithDefaults() *KindValidateRequest {
	this := KindValidateRequest{}
	return &this
}

// GetParameters returns the Parameters field value if set, zero value otherwise.
func (o *KindValidateRequest) GetParameters() map[string]interface{} {
	if o == nil || IsNil(o.Parameters) {
		var ret map[string]interface{}
		return ret
	}
	return o.Parameters
}

// GetParametersOk returns a tuple with the Parameters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KindValidateRequest) GetParametersOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Parameters) {
		return map[string]interface{}{}, false
	}
	return o.Parameters, true
}

// HasParameters returns a boolean if a field has been set.
func (o *KindValidateRequest) HasParameters() bool {
	if o != nil && !IsNil(o.Parameters) {
		return true
	}

	return false
}

// SetParameters gets a reference to the given map[string]interface{} and assigns it to the Parameters field.
func (o *KindValidateRequest) SetParameters(v map[string]interface{}) {
	o.Parameters = v
}

func (o KindValidateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o KindValidateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Parameters) {
		toSerialize["parameters"] = o.Parameters
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *KindValidateRequest) UnmarshalJSON(data []byte) (err error) {
	varKindValidateRequest := _KindValidateRequest{}

	err = json.Unmarshal(data, &varKindValidateRequest)

	if err != nil {
		return err
	}

	*o = KindValidateRequest(varKindValidateRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "parameters")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableKindValidateRequest struct {
	value *KindValidateRequest
	isSet bool
}

func (v NullableKindValidateRequest) Get() *KindValidateRequest {
	return v.value
}

func (v *NullableKindValidateRequest) Set(val *KindValidateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableKindValidateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableKindValidateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKindValidateRequest(val *KindValidateRequest) *NullableKindValidateRequest {
	return &NullableKindValidateRequest{value: val, isSet: true}
}

func (v NullableKindValidateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKindValidateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
