/*
Integrations API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
	"fmt"
)

// checks if the AuthValidateResponseSerializer type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuthValidateResponseSerializer{}

// AuthValidateResponseSerializer struct for AuthValidateResponseSerializer
type AuthValidateResponseSerializer struct {
	IsValid              bool                     `json:"isValid"`
	Error                NullableString           `json:"error,omitempty"`
	FieldResults         []map[string]interface{} `json:"fieldResults,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _AuthValidateResponseSerializer AuthValidateResponseSerializer

// NewAuthValidateResponseSerializer instantiates a new AuthValidateResponseSerializer object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthValidateResponseSerializer(isValid bool) *AuthValidateResponseSerializer {
	this := AuthValidateResponseSerializer{}
	this.IsValid = isValid
	return &this
}

// NewAuthValidateResponseSerializerWithDefaults instantiates a new AuthValidateResponseSerializer object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthValidateResponseSerializerWithDefaults() *AuthValidateResponseSerializer {
	this := AuthValidateResponseSerializer{}
	return &this
}

// GetIsValid returns the IsValid field value
func (o *AuthValidateResponseSerializer) GetIsValid() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsValid
}

// GetIsValidOk returns a tuple with the IsValid field value
// and a boolean to check if the value has been set.
func (o *AuthValidateResponseSerializer) GetIsValidOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsValid, true
}

// SetIsValid sets field value
func (o *AuthValidateResponseSerializer) SetIsValid(v bool) {
	o.IsValid = v
}

// GetError returns the Error field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AuthValidateResponseSerializer) GetError() string {
	if o == nil || IsNil(o.Error.Get()) {
		var ret string
		return ret
	}
	return *o.Error.Get()
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AuthValidateResponseSerializer) GetErrorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Error.Get(), o.Error.IsSet()
}

// HasError returns a boolean if a field has been set.
func (o *AuthValidateResponseSerializer) HasError() bool {
	if o != nil && o.Error.IsSet() {
		return true
	}

	return false
}

// SetError gets a reference to the given NullableString and assigns it to the Error field.
func (o *AuthValidateResponseSerializer) SetError(v string) {
	o.Error.Set(&v)
}

// SetErrorNil sets the value for Error to be an explicit nil
func (o *AuthValidateResponseSerializer) SetErrorNil() {
	o.Error.Set(nil)
}

// UnsetError ensures that no value is present for Error, not even an explicit nil
func (o *AuthValidateResponseSerializer) UnsetError() {
	o.Error.Unset()
}

// GetFieldResults returns the FieldResults field value if set, zero value otherwise.
func (o *AuthValidateResponseSerializer) GetFieldResults() []map[string]interface{} {
	if o == nil || IsNil(o.FieldResults) {
		var ret []map[string]interface{}
		return ret
	}
	return o.FieldResults
}

// GetFieldResultsOk returns a tuple with the FieldResults field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthValidateResponseSerializer) GetFieldResultsOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.FieldResults) {
		return nil, false
	}
	return o.FieldResults, true
}

// HasFieldResults returns a boolean if a field has been set.
func (o *AuthValidateResponseSerializer) HasFieldResults() bool {
	if o != nil && !IsNil(o.FieldResults) {
		return true
	}

	return false
}

// SetFieldResults gets a reference to the given []map[string]interface{} and assigns it to the FieldResults field.
func (o *AuthValidateResponseSerializer) SetFieldResults(v []map[string]interface{}) {
	o.FieldResults = v
}

func (o AuthValidateResponseSerializer) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuthValidateResponseSerializer) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["isValid"] = o.IsValid
	if o.Error.IsSet() {
		toSerialize["error"] = o.Error.Get()
	}
	if !IsNil(o.FieldResults) {
		toSerialize["fieldResults"] = o.FieldResults
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AuthValidateResponseSerializer) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"isValid",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAuthValidateResponseSerializer := _AuthValidateResponseSerializer{}

	err = json.Unmarshal(data, &varAuthValidateResponseSerializer)

	if err != nil {
		return err
	}

	*o = AuthValidateResponseSerializer(varAuthValidateResponseSerializer)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "isValid")
		delete(additionalProperties, "error")
		delete(additionalProperties, "fieldResults")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAuthValidateResponseSerializer struct {
	value *AuthValidateResponseSerializer
	isSet bool
}

func (v NullableAuthValidateResponseSerializer) Get() *AuthValidateResponseSerializer {
	return v.value
}

func (v *NullableAuthValidateResponseSerializer) Set(val *AuthValidateResponseSerializer) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthValidateResponseSerializer) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthValidateResponseSerializer) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthValidateResponseSerializer(val *AuthValidateResponseSerializer) *NullableAuthValidateResponseSerializer {
	return &NullableAuthValidateResponseSerializer{value: val, isSet: true}
}

func (v NullableAuthValidateResponseSerializer) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthValidateResponseSerializer) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
