/*
Integrations API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
	"fmt"
)

// checks if the CreateConnectionRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateConnectionRequest{}

// CreateConnectionRequest Mirrors “createConnection(vendor_key, new_name, integration_type)“ args.
type CreateConnectionRequest struct {
	ConnectionName       string         `json:"connectionName"`
	IntegrationType      NullableString `json:"integrationType,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CreateConnectionRequest CreateConnectionRequest

// NewCreateConnectionRequest instantiates a new CreateConnectionRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateConnectionRequest(connectionName string) *CreateConnectionRequest {
	this := CreateConnectionRequest{}
	this.ConnectionName = connectionName
	return &this
}

// NewCreateConnectionRequestWithDefaults instantiates a new CreateConnectionRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateConnectionRequestWithDefaults() *CreateConnectionRequest {
	this := CreateConnectionRequest{}
	return &this
}

// GetConnectionName returns the ConnectionName field value
func (o *CreateConnectionRequest) GetConnectionName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ConnectionName
}

// GetConnectionNameOk returns a tuple with the ConnectionName field value
// and a boolean to check if the value has been set.
func (o *CreateConnectionRequest) GetConnectionNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ConnectionName, true
}

// SetConnectionName sets field value
func (o *CreateConnectionRequest) SetConnectionName(v string) {
	o.ConnectionName = v
}

// GetIntegrationType returns the IntegrationType field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateConnectionRequest) GetIntegrationType() string {
	if o == nil || IsNil(o.IntegrationType.Get()) {
		var ret string
		return ret
	}
	return *o.IntegrationType.Get()
}

// GetIntegrationTypeOk returns a tuple with the IntegrationType field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateConnectionRequest) GetIntegrationTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.IntegrationType.Get(), o.IntegrationType.IsSet()
}

// HasIntegrationType returns a boolean if a field has been set.
func (o *CreateConnectionRequest) HasIntegrationType() bool {
	if o != nil && o.IntegrationType.IsSet() {
		return true
	}

	return false
}

// SetIntegrationType gets a reference to the given NullableString and assigns it to the IntegrationType field.
func (o *CreateConnectionRequest) SetIntegrationType(v string) {
	o.IntegrationType.Set(&v)
}

// SetIntegrationTypeNil sets the value for IntegrationType to be an explicit nil
func (o *CreateConnectionRequest) SetIntegrationTypeNil() {
	o.IntegrationType.Set(nil)
}

// UnsetIntegrationType ensures that no value is present for IntegrationType, not even an explicit nil
func (o *CreateConnectionRequest) UnsetIntegrationType() {
	o.IntegrationType.Unset()
}

func (o CreateConnectionRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateConnectionRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["connectionName"] = o.ConnectionName
	if o.IntegrationType.IsSet() {
		toSerialize["integrationType"] = o.IntegrationType.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateConnectionRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"connectionName",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateConnectionRequest := _CreateConnectionRequest{}

	err = json.Unmarshal(data, &varCreateConnectionRequest)

	if err != nil {
		return err
	}

	*o = CreateConnectionRequest(varCreateConnectionRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "connectionName")
		delete(additionalProperties, "integrationType")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateConnectionRequest struct {
	value *CreateConnectionRequest
	isSet bool
}

func (v NullableCreateConnectionRequest) Get() *CreateConnectionRequest {
	return v.value
}

func (v *NullableCreateConnectionRequest) Set(val *CreateConnectionRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateConnectionRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateConnectionRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateConnectionRequest(val *CreateConnectionRequest) *NullableCreateConnectionRequest {
	return &NullableCreateConnectionRequest{value: val, isSet: true}
}

func (v NullableCreateConnectionRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateConnectionRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
