/*
Integrations API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
)

// checks if the KindSaveRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &KindSaveRequest{}

// KindSaveRequest struct for KindSaveRequest
type KindSaveRequest struct {
	Parameters           []map[string]interface{} `json:"parameters,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _KindSaveRequest KindSaveRequest

// NewKindSaveRequest instantiates a new KindSaveRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKindSaveRequest() *KindSaveRequest {
	this := KindSaveRequest{}
	return &this
}

// NewKindSaveRequestWithDefaults instantiates a new KindSaveRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKindSaveRequestWithDefaults() *KindSaveRequest {
	this := KindSaveRequest{}
	return &this
}

// GetParameters returns the Parameters field value if set, zero value otherwise.
func (o *KindSaveRequest) GetParameters() []map[string]interface{} {
	if o == nil || IsNil(o.Parameters) {
		var ret []map[string]interface{}
		return ret
	}
	return o.Parameters
}

// GetParametersOk returns a tuple with the Parameters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KindSaveRequest) GetParametersOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.Parameters) {
		return nil, false
	}
	return o.Parameters, true
}

// HasParameters returns a boolean if a field has been set.
func (o *KindSaveRequest) HasParameters() bool {
	if o != nil && !IsNil(o.Parameters) {
		return true
	}

	return false
}

// SetParameters gets a reference to the given []map[string]interface{} and assigns it to the Parameters field.
func (o *KindSaveRequest) SetParameters(v []map[string]interface{}) {
	o.Parameters = v
}

func (o KindSaveRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o KindSaveRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Parameters) {
		toSerialize["parameters"] = o.Parameters
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *KindSaveRequest) UnmarshalJSON(data []byte) (err error) {
	varKindSaveRequest := _KindSaveRequest{}

	err = json.Unmarshal(data, &varKindSaveRequest)

	if err != nil {
		return err
	}

	*o = KindSaveRequest(varKindSaveRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "parameters")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableKindSaveRequest struct {
	value *KindSaveRequest
	isSet bool
}

func (v NullableKindSaveRequest) Get() *KindSaveRequest {
	return v.value
}

func (v *NullableKindSaveRequest) Set(val *KindSaveRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableKindSaveRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableKindSaveRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKindSaveRequest(val *KindSaveRequest) *NullableKindSaveRequest {
	return &NullableKindSaveRequest{value: val, isSet: true}
}

func (v NullableKindSaveRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKindSaveRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
