/*
Integrations API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
	"fmt"
)

// checks if the KindSelectRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &KindSelectRequest{}

// KindSelectRequest Mirrors “connSetCheckbox(kind, selected: bool)“'s single “selected“ argument.
type KindSelectRequest struct {
	Selected             bool `json:"selected"`
	AdditionalProperties map[string]interface{}
}

type _KindSelectRequest KindSelectRequest

// NewKindSelectRequest instantiates a new KindSelectRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKindSelectRequest(selected bool) *KindSelectRequest {
	this := KindSelectRequest{}
	this.Selected = selected
	return &this
}

// NewKindSelectRequestWithDefaults instantiates a new KindSelectRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKindSelectRequestWithDefaults() *KindSelectRequest {
	this := KindSelectRequest{}
	return &this
}

// GetSelected returns the Selected field value
func (o *KindSelectRequest) GetSelected() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Selected
}

// GetSelectedOk returns a tuple with the Selected field value
// and a boolean to check if the value has been set.
func (o *KindSelectRequest) GetSelectedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Selected, true
}

// SetSelected sets field value
func (o *KindSelectRequest) SetSelected(v bool) {
	o.Selected = v
}

func (o KindSelectRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o KindSelectRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["selected"] = o.Selected

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *KindSelectRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"selected",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varKindSelectRequest := _KindSelectRequest{}

	err = json.Unmarshal(data, &varKindSelectRequest)

	if err != nil {
		return err
	}

	*o = KindSelectRequest(varKindSelectRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "selected")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableKindSelectRequest struct {
	value *KindSelectRequest
	isSet bool
}

func (v NullableKindSelectRequest) Get() *KindSelectRequest {
	return v.value
}

func (v *NullableKindSelectRequest) Set(val *KindSelectRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableKindSelectRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableKindSelectRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKindSelectRequest(val *KindSelectRequest) *NullableKindSelectRequest {
	return &NullableKindSelectRequest{value: val, isSet: true}
}

func (v NullableKindSelectRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKindSelectRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
